Breed show page
saulleee/happy-pets pull request #2
Opened 2021-11-15 21:02 UTC by Grullnor

updated the pet show page and routes to allow the pet's name and description as well as the breed objects, and to redirect from /pets/:id/breeds to simply pets/:id .

2021-11-15 21:27 UTC, dovakeen118 requested changes
Lot's of code clean up required here and realigning on the scope of this branch

2021-11-15 21:27 UTC, dovakeen118 commented on app/controllers/concerns/api/v1/breeds_controller.rb
> +  # end
We should remove unused, commented code

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/BreedShowContainer.js
> +            />
props should be indented, nested under the component `<BreedShow`

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/PetShowContainer.js
> +          debugger
REMOVE DEBUGGER

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/PetShowContainer.js
> +    const petTiles = pet["breeds"].map((breed) => {
Might want to use dot notation rather than bracket notation to be more consistent within the React codebase

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/PetsIndexContainer.js
> +        //   debugger;
REMOVE DEBUGGERS!

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/PetsIndexContainer.js
> +    // debugger
DEBUGGER

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/PetsIndexContainer.js
> +}
remove extra empty lines

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/PetsIndexContainer.js
> +const PetsIndexContainer = (props) => {
The name of this feature branch is the Breed Show page, we shouldn't see code related to other features

2021-11-15 21:27 UTC, dovakeen118 commented on app/views/pets/index.html.erb
> +    </li>
The Pets Index is out of scope for this feature branch, but if the Pets index is moved to a React component then the ERB template can be removed (should be done in the appropriate branch)

2021-11-15 21:27 UTC, dovakeen118 commented on config/routes.rb
> +  # end
remove unused code

2021-11-15 21:27 UTC, dovakeen118 commented on db/schema.rb
> +  create_table "comments", force: :cascade do |t|
This branch is for Breed Show, this comments migration is out of scope

2021-11-15 21:27 UTC, dovakeen118 commented on db/schema.rb
> +  create_table "questions", force: :cascade do |t|
Not sure what `questions` is for? This is out of scope

2021-11-15 21:27 UTC, dovakeen118 commented on app/controllers/concerns/api/v1/breeds_controller.rb
> +  def show
The Breed show page should either be in React or an ERB template, we don't need the action in both controllers. Choose the one that corresponds to your view of this data.

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/BreedShowContainer.js
> +          debugger
DEBUGGER

2021-11-15 21:27 UTC, dovakeen118 commented on app/javascript/react/components/BreedShowContainer.js
> +    return(
Watch your indentation and use of empty lines. This file is inconsistent with others in this app

2021-11-15 21:27 UTC, dovakeen118 commented on app/controllers/breeds_controller.rb
> +    @breed = @breeds.find_by_id(params[:id])
This looks like an interesting association. A Pet has many Breeds, and a Breed belongs to one Pet? I would think the opposite to be true, the `Breed` Golden Retriever can `have many` `Pets`, Allie, Buddy, etc., and a `Pet` `belongs to` a `Breed`. If you have 2 pets that are both a Golden, your current database appears to then have "Golden Retriever" as a breed multiple times, because there are multiple pets with that breed.

2021-11-16 17:55 UTC, nwalberts requested changes

2021-11-16 17:55 UTC, nwalberts commented on app/controllers/concerns/api/v1/breeds_controller.rb
> +    render json: Pet.find_by_id(params[:pet_id]).breeds.find_by_id(params[:id])
this code is executing too many queries. 

You can just run `Breed.find(params[:id])`. Id's are unique, so you dont need to know the pet. 

Also, find_by_id can always just be replaced with `find`

2021-11-16 17:55 UTC, nwalberts commented on app/controllers/concerns/api/v1/pets_controller.rb
> +    render json: {name: pet.name, description: pet.description, breeds: pet.breeds}
I see you've added activemodel serializers, AND we talked about this in person! Add your serializer here!

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/BreedShowContainer.js
> +  )
you dont need the div, you can just render BreedShow!

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetShow.js
> +        <Link to={`/pets/${props.petId}/breeds/${props.breedId}`}>
you can simplify this even more in fact, but simply making the route: 

`/breeds/${props.breedId}`

this is in line with my comment on your controller too. This means you will need to update your routes.rb accordingly

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetShow.js
> +const PetShow = (props) => {
this name of the component is coming off as pretty confusing given the naming convention for some of your other components. AND its not about Pets at all, but for a breed! Lets call this `BreedTile` instead

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetShowContainer.js
> +    }
nice job!

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetShowContainer.js
> +    })
these are not pet data, but breed data! update your names otherwise this will get confusing quickly!

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetShowContainer.js
> +          <h3>{pet["description"]}</h3>
rather than [] notation, we want to follow default style convention of `pet.name` and `pet.description` for consistency. Update this across your PR

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetsIndex.js
> +const PetsIndex = (props) => {
this should be renamed to `PetTile` otherwise it will be very confusing.

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetsIndex.js
> +        <Link to={`/pets/${props.id}/breeds`}>
while the pet show page is also technically the breeds index page, we want to shoot for as shallow nesting as possible. update this to `/pets/${props.id}`. No need for `breeds` as a part of the path (even if it works, its better Rails convention)

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetsIndexContainer.js
> +    // debugger
Still in here!!!

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetsIndexContainer.js
> +          />
indent in lines 29-31

2021-11-16 17:55 UTC, nwalberts commented on app/javascript/react/components/PetsIndexContainer.js
> +}
In additon to Kerrin's comment, we shouldnt have all of the pet tiles sitting in an H1!! Instead render them in a better element for nested elements, like a div. And consider adding a descriptive header at the top of this page

2021-11-16 17:55 UTC, nwalberts commented on app/views/breeds/show.html.erb
> +<h3><%= @breed.rating %></h3>
remove this ERB, as you now have it in React

2021-11-16 17:55 UTC, nwalberts commented on app/views/breeds/index.html.erb
>  </ul>
remove this ERB, as you now have the feature in React

2021-11-16 17:55 UTC, nwalberts commented on config/routes.rb
> +  get '/pets/:id/breeds/:id', to: 'homes#index'
per my comments above, you will have to update these nested paths

2021-11-16 17:55 UTC, nwalberts commented on spec/features/user_sees_breed_show_page_spec.rb
> +    b3 = Breed.create(name: "Tabby", description: "a cat", pet: p2)
good work, but Im going to ask that your variables be more descriptive than p1 and instead be pet1. I know its frustrating, but this starting to snowball and add confusion the larger the codebase gets

2021-11-16 17:55 UTC, nwalberts commented on spec/features/user_sees_breed_show_page_spec.rb
> +end
actually, this entire test will be removed as you now have the feature in react. 

I need to see controller testing for the API controllers as well before I merge in this PR

2021-11-16 18:27 UTC, Grullnor commented on app/javascript/react/components/PetShowContainer.js
> +    })
I went ahead and changed some variable names to reflect their usage better.

petId -> id
name -> breedName

I also went ahead and make the key variable equal to the pet id rather than the breed id.

Do you think that is distinct enough?

2021-11-16 20:04 UTC, nwalberts commented on app/javascript/react/components/App.js
> +        <Route exact path="/pets/:id/breeds/:id" component={BreedShowContainer} />
the path should be JUST `/breeds/:id` for this breed show

2021-11-16 20:08 UTC, nwalberts commented on app/javascript/react/components/BreedShowContainer.js
> +      const response = await fetch(`/api/v1${props.match.url}`)
womp. I thought we got rid of `props.match.url`? this should be `api/v1/breeds/${props.match.params.id}`

2021-11-16 20:40 UTC, merged